---
apiVersion: v1
kind: Service
metadata:
  name: webappsvc
spec:
  type: LoadBalancer
  selector:
    app: sravanwebapp
  ports:
    - port: 80                                            
      targetPort: 8080                                           

